src/Entity/Developer.php
<?php

namespace App\Entity;

use App\Entity\Skills;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\DeveloperRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: DeveloperRepository::class)]
#[Vich\Uploadable]
class Developer implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\Length(min: 2, max: 180)]
    private ?string $username = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: 'string')]
    private ?string $password = null;

    private ?string $plainPassword = null;

    #[ORM\Column(type: 'string', length: 32)]
    #[Assert\Length(min: 2, max: 32)]
    private ?string $first_name = null;

    #[ORM\Column(type: 'string', length: 32)]
    #[Assert\Length(min: 2, max: 32)]
    private ?string $last_name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $biography = null;

    #[ORM\Column(type:'string', length: 255)]
    #[Assert\Email()]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $github_link = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $linkedin_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $youtube_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture_name = null;

    #[Vich\UploadableField(mapping: 'pictureDeveloper', fileNameProperty: 'picture_name')]
    private ?File $picture_file = null;
    
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)] 
    private ?\DateTimeImmutable $update_At = null;

    

    #[ORM\OneToMany(mappedBy: 'SkillDeveloper', targetEntity: Skills::class)]
    private Collection $Skill;

    public function __construct()
    {
        $this->Skill = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): static
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        
        $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(string $biography): static
    {
        $this->biography = $biography;

        return $this;
    }
    
    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getGithubLink(): ?string
    {
        return $this->github_link;
    }

    public function setGithubLink(string $github_link): static
    {
        $this->github_link = $github_link;

        return $this;
    }

    public function getLinkedinLink(): ?string
    {
        return $this->linkedin_link;
    }

    public function setLinkedinLink(string $linkedin_link): static
    {
        $this->linkedin_link = $linkedin_link;

        return $this;
    }

    public function getYoutubeLink(): ?string
    {
        return $this->youtube_link;
    }

    public function setYoutubeLink(?string $youtube_link): static
    {
        $this->youtube_link = $youtube_link;

        return $this;
    }

    public function getPictureName(): ?string
    {
        return $this->picture_name;
    }

    public function setPictureName(?string $picture_name): static
    {
        $this->picture_name = $picture_name;

        return $this;
    }
    
    public function setPictureFile(?File $picture_file): static
    {
        $this->picture_file = $picture_file;

        if (null !== $picture_file) {
            $this->update_At = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getPictureFile(): ?File
    {
        return $this->picture_file;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->update_At;
    }


    public function setUpdateAt(?\DateTimeImmutable $updateAt): self
    {
        $this->update_At = $updateAt;

        return $this;
    }

    /**
     * @return Collection<int, Skills>
     */
    public function getSkill(): Collection
    {
        return $this->Skill;
    }

    public function addSkill(Skills $skill): static
    {
        if (!$this->Skill->contains($skill)) {
            $this->Skill->add($skill);
            $skill->setSkillDeveloper($this);
        }

        return $this;
    }

    public function removeSkill(Skills $skill): static
    {
        if ($this->Skill->removeElement($skill)) {
            // set the owning side to null (unless already changed)
            if ($skill->getSkillDeveloper() === $this) {
                $skill->setSkillDeveloper(null);
            }
        }

        return $this;
    }
}

templates/_partials/_flash.html.twig
{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="position-absolute top-50 start-50 translate-middle" style="z-index: 1000;">
            <div class="alert alert-{{ label }} alert-dismissible fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                <div class="alert-message">
                    {{ message|raw }}
                </div>
            </div>
        </div>
    {% endfor %}
{% endfor %}

templates/_partials/_footer.html.twig
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 px-3 text-bg-dark">
	<div class="col-md-4 d-flex align-items-center mx-auto mx-md-0">
		<span class="mb-3 mb-md-0">
			© 2023 - Christopher Bichon.
		</span>
	</div>

	<ul
		class="nav col-md-4 justify-content-end list-unstyled d-flex mx-auto mx-md-0">
		{# <li class="ms-3 nav-item">
							<a class="nav-link text-white" href="#">
								<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-youtube" viewbox="0 0 16 16">
									<path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408z"/>
								</svg>
							</a>
						</li>
						<li class="ms-3 nav-item">
							<a class="nav-link text-white" href="#">
								<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-twitter" viewbox="0 0 16 16">
									<path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15"/>
								</svg>
							</a>
						</li> #}
		<li class="ms-3 nav-item">
			<a class="nav-link text-white" href="{{ developer.LinkedinLink }}" target="_blank" aria-label="Mon Profil Linkedin" title="Mon Profil Linkedin">
				<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-linkedin" viewbox="0 0 16 16">
					<path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401m-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4"/>
				</svg>
			</a>
		</li>
		<li class="ms-3 nav-item">
			<a class="nav-link text-white" href="{{ developer.GithubLink}}" target="_blank" aria-label="Mon GitHub" title="Mon GitHub">
				<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-github" viewbox="0 0 16 16">
					<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
				</svg>
			</a>
		</li>
	</ul>
</footer>

templates/_partials/_header.html.twig
<header>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3" aria-label="navBar">
		<a class="navbar-brand" href="{{ path('app_home') }}">
			<h3>
				{{developer.LastName}} {{developer.FirstName}}
			</h3>
		</a>
		<button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>


		<div class="navbar-collapse collapse" id="navbars" style="">
		<div class="dropdown" id="customDropdown">
			<button class="btn btn-outline-light ms-5 d-none d-lg-inline" type="button" id="dropdownContact" data-bs-toggle="dropdown" aria-expanded="false">
				Contact
			</button>
			<ul class="dropdown-menu" aria-labelledby="dropdownContact">
				<li><a class="dropdown-item" href="{{ path('app_contact') }}" aria-label="Me contacter"><i class="bi bi-envelope"></i> Me Contacter</a></li>
				<li><a class="dropdown-item" href="{{ developer.GithubLink }}" target="_blank" aria-label="Mon GitHub"><i class="bi bi-github"></i> GitHub</a></li>
				<li><a class="dropdown-item" href="{{ developer.LinkedinLink }}" target="_blank" aria-label="Mon Linkedin"><i class="bi bi-linkedin"></i> LinkedIn</a></li>
			</ul>
		</div>
			<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
				{# <li class="nav-item">
					<a class="nav-link" href="#">
                    <span class="d-none d-lg-inline">
						<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-youtube" viewbox="0 0 16 16">
							<path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408z"/>
						</svg>
                    </span>
                    <span class="d-inline d-lg-none">Youtube</span>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link">
                    <span class="d-none d-lg-inline">
						<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-twitter" viewbox="0 0 16 16">
							<path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15"/>
						</svg>
                        </span>
                    <span class="d-inline d-lg-none">Twitter</span>
					</a>
				</li> #}
				<li class="nav-item">
					<a class="nav-link" href="{{ developer.LinkedinLink }}" target="_blank" aria-label="Mon Profil Linkedin" title="Mon Profil Linkedin">
                    <span class="d-none d-lg-inline">
						<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-linkedin" viewbox="0 0 16 16">
							<path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401m-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4"/>
						</svg>
                        </span>
                    <span class="d-inline d-lg-none">LinkedIn</span>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ developer.GithubLink}}" target="_blank" aria-label="Mon GitHub" title="Mon GitHub">
                    <span class="d-none d-lg-inline">
						<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-github" viewbox="0 0 16 16">
							<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
						</svg>
                        </span>
                    <span class="d-inline d-lg-none">GitHub</span>
					</a>
				</li>
			</ul>
		</div>
		
	</nav>
</header>
	

templates/_partials/_headerBottom.html.twig
<header>
    <div class="px-3 m-5">
		<div class="row flex-lg-row-reverse align-items-center g-5">
			<div class="col-10 col-sm-8 col-lg-6">
				<img src="{{ asset('uploads/developerProfil/' ~ developer.pictureName) }}" class="d-none d-lg-block d-xl-block mx-lg-auto object-fit-cover profile-image" alt="Profil" width="450" height="450" loading="lazy">
			</div>
			<div class="col-lg-6">
				<span class="fs-2 fw-bolder fst-italic text-body-emphasis mb-3 text-uppercase">
					Un monde sans limite
				</span>
                <h2>Bonjour Je suis {{ developer.FirstName }}<h2>
				<p class="lead lh-base d-none d-lg-block d-xl-block">
					{{ developer.biography }}
				</p>
				
				<a class="btn btn-dark ms-5 d-inline d-lg-none"href="{{ path('app_contact') }}" aria-label="Me contacter"><i class="bi bi-envelope"></i> Contact</a>
			
			</div>
		</div>
	</div>
</header>
	