src/Entity/Projects.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProjectsRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ProjectsRepository::class)]
#[Vich\Uploadable]
class Projects
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type:'string', length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $github_link = null;

    #[ORM\Column(length: 255)]
    private ?string $website_link = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank()]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)] 
    private ?\DateTimeImmutable $update_At = null;

    #[ORM\ManyToMany(targetEntity: Langages::class, inversedBy: 'Langage')]
    private Collection $langages;

    #[ORM\Column(length: 255, type:'string', nullable: true)]
    private ?string $screen_name = null;

    #[Vich\UploadableField(mapping: 'screenProject', fileNameProperty: 'screen_name')]
    private ?File $screen_file = null;

    public function __construct()
    {
        $this->langages = new ArrayCollection();
        // $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getGithubLink(): ?string
    {
        return $this->github_link;
    }

    public function setGithubLink(string $github_link): static
    {
        $this->github_link = $github_link;

        return $this;
    }

    public function getWebsiteLink(): ?string
    {
        return $this->website_link;
    }

    public function setWebsiteLink(string $website_link): static
    {
        $this->website_link = $website_link;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->update_At;
    }


    public function setUpdateAt(?\DateTimeImmutable $updateAt): self
    {
        $this->update_At = $updateAt;

        return $this;
    }

    /**
     * @return Collection<int, Langages>
     */
    public function getLangages(): Collection
    {
        return $this->langages;
    }

    public function addLangage(Langages $langage): static
    {
        if (!$this->langages->contains($langage)) {
            $this->langages->add($langage);
        }

        return $this;
    }

    public function removeLangage(Langages $langage): static
    {
        $this->langages->removeElement($langage);

        return $this;
    }


    public function getScreenName(): ?string
    {
        return $this->screen_name;
    }

    public function setScreenName(?string $screen_name): self
    {
        $this->screen_name = $screen_name;

        return $this;
    }

    public function setScreenFile(?File $screen_file): static
    {
        $this->screen_file = $screen_file;

        if (null !== $screen_file) {
            $this->update_At = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getScreenFile(): ?File
    {
        return $this->screen_file;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\DeveloperRepository;
use App\Repository\ProjectsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(DeveloperRepository $developerRepository, ProjectsRepository $projectsRepository): Response
    {   
        $developer = $developerRepository->find(1);
        $projects = $projectsRepository->findBy([], ['created_at' => 'DESC'], 5);

        // dd($projects);


        return $this->render('home/index.html.twig', [
            'developer' => $developer,
            'projects' => $projects,            
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Krystdev - Portfolio
{% endblock %}

{% block body %}
{% include "_partials/_headerBottom.html.twig" %}

	<div class="album py-5">
		<div class="container">
			<div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
				{% for project in projects %}
					<div class="col">
						<div class="card h-100 shadow-sm d-flex flex-column">
							<img src="{{ asset("uploads/projects/thumbnails/" ~ project.screenName) }}" alt="{{ project.title }}" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ project.description }}" data-bs-offset="0,-50" data-bs-delay="100" data-bs-delay-hide="1000">
							<div class="card-body d-flex flex-column">
								<div class="mt-auto">
									<div class="d-flex justify-content-between align-items-center">
										<div class="btn-group flex-wrap">
											<a href="{{ project.webSiteLink }}" target="_blank" type="button" class="btn btn-sm btn-outline-secondary">
												Voir
											</a>
											<button type="button" class="btn btn-sm btn-outline-secondary" data-controller="tooltip" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title=" {% for langage in project.langages %}
																								{{ langage.getLangage() }}{% if not loop.last %}, {% endif %}
																								{% endfor %}" data-bs-offset="0,0" data-bs-delay="100" data-bs-delay-hide="1000">
												Languages
											</button>
											<a href="{{ project.gitHubLink }}" target="_blank" type="button" class="btn btn-sm btn-outline-secondary">
												GitHub
											</a>
										</div>
										<small class="text-body-secondary"></small>
									</div>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
			{# A remettre seulement quand le nombre de projets depassera les 5 #}
			{# <div class="d-flex justify-content-center">
				<button type="button" class="btn btn-dark m-2">
					Mes réalisations
				</button>
			</div> #}
		</div>
	</div>
{% endblock %}